#!/usr/bin/env bash

## UNICODE to ASCII

NAME="UNICODE_to_ASCII"
OUT="$(dirname ${0})/${NAME}.lua"

echo "Generating table for ${NAME} ..." >&2
if [[ -e "${OUT}" ]]; then
	echo "File ${OUT} already exists, skipping!" >&2
else
	$(dirname ${0})/../convert-charsets-tools/generate-konwert-ascii-mappings-table.sh > "${OUT}"
fi

## UNICODE to SGML

NAME="UNICODE_to_SGML"
OUT="$(dirname ${0})/${NAME}.lua"

echo "Generating table for ${NAME} ..." >&2
if [[ -e "${OUT}" ]]; then
	echo "File ${OUT} already exists, skipping!" >&2
else
	$(dirname ${0})/../convert-charsets-tools/generate-unicode-org-mappings-table-sgml.sh > "${OUT}"
fi

## NATIVE to UNICODE

TABLES="
ETSI/GSM0338.TXT
ISO8859/8859-1.TXT
ISO8859/8859-2.TXT
ISO8859/8859-3.TXT
ISO8859/8859-4.TXT
ISO8859/8859-5.TXT
ISO8859/8859-6.TXT
ISO8859/8859-7.TXT
ISO8859/8859-8.TXT
ISO8859/8859-9.TXT
ISO8859/8859-10.TXT
ISO8859/8859-11.TXT
ISO8859/8859-13.TXT
ISO8859/8859-14.TXT
ISO8859/8859-15.TXT
ISO8859/8859-16.TXT
VENDORS/MICSFT/PC/CP437.TXT
VENDORS/MICSFT/PC/CP737.TXT
VENDORS/MICSFT/PC/CP775.TXT
VENDORS/MICSFT/PC/CP850.TXT
VENDORS/MICSFT/PC/CP852.TXT
VENDORS/MICSFT/PC/CP855.TXT
VENDORS/MICSFT/PC/CP857.TXT
VENDORS/MICSFT/PC/CP860.TXT
VENDORS/MICSFT/PC/CP861.TXT
VENDORS/MICSFT/PC/CP862.TXT
VENDORS/MICSFT/PC/CP863.TXT
VENDORS/MICSFT/PC/CP864.TXT
VENDORS/MICSFT/PC/CP865.TXT
VENDORS/MICSFT/PC/CP866.TXT
VENDORS/MICSFT/PC/CP869.TXT
VENDORS/MICSFT/WINDOWS/CP874.TXT
VENDORS/MICSFT/WINDOWS/CP932.TXT
VENDORS/MICSFT/WINDOWS/CP936.TXT
VENDORS/MICSFT/WINDOWS/CP949.TXT
VENDORS/MICSFT/WINDOWS/CP950.TXT
VENDORS/MICSFT/WINDOWS/CP1250.TXT
VENDORS/MICSFT/WINDOWS/CP1251.TXT
VENDORS/MICSFT/WINDOWS/CP1252.TXT
VENDORS/MICSFT/WINDOWS/CP1253.TXT
VENDORS/MICSFT/WINDOWS/CP1254.TXT
VENDORS/MICSFT/WINDOWS/CP1255.TXT
VENDORS/MICSFT/WINDOWS/CP1256.TXT
VENDORS/MICSFT/WINDOWS/CP1257.TXT
VENDORS/MICSFT/WINDOWS/CP1258.TXT
VENDORS/APPLE/ARABIC.TXT:MAC
VENDORS/APPLE/CELTIC.TXT:MAC
VENDORS/APPLE/CENTEURO.TXT:MAC
VENDORS/APPLE/CROATIAN.TXT:MAC
VENDORS/APPLE/CYRILLIC.TXT:MAC
VENDORS/APPLE/DEVANAGA.TXT:MAC
VENDORS/APPLE/DINGBATS.TXT:MAC
VENDORS/APPLE/FARSI.TXT:MAC
VENDORS/APPLE/GAELIC.TXT:MAC
VENDORS/APPLE/GREEK.TXT:MAC
VENDORS/APPLE/GUJARATI.TXT:MAC
VENDORS/APPLE/GURMUKHI.TXT:MAC
VENDORS/APPLE/HEBREW.TXT:MAC
VENDORS/APPLE/CHINSIMP.TXT:MAC
VENDORS/APPLE/CHINTRAD.TXT:MAC
VENDORS/APPLE/ICELAND.TXT:MAC
VENDORS/APPLE/INUIT.TXT:MAC
VENDORS/APPLE/JAPANESE.TXT:MAC
VENDORS/APPLE/KEYBOARD.TXT:MAC
VENDORS/APPLE/KOREAN.TXT:MAC
VENDORS/APPLE/ROMANIAN.TXT:MAC
VENDORS/APPLE/ROMAN.TXT:MAC
VENDORS/APPLE/SYMBOL.TXT:MAC
VENDORS/APPLE/THAI.TXT:MAC
VENDORS/APPLE/TURKISH.TXT:MAC
VENDORS/MISC/ATARIST.TXT
VENDORS/MISC/KOI8-R.TXT
VENDORS/MISC/KOI8-U.TXT
"

for I in ${TABLES}; do
	[[ "${I##*:}" != "${I}" ]] && NAME_PREFIX="${I##*:}_" || unset NAME_PREFIX
	FILE="${I##*/}" BASENAME="${NAME_PREFIX}${FILE%.*}" NAME="${BASENAME//-/_}_to_UNICODE"
	OUT="$(dirname ${0})/${NAME}.lua"
	echo "Generating table for ${NAME} ..." >&2
	if [[ -e "${OUT}" ]]; then
		echo "File ${OUT} already exists, skipping!" >&2
		continue
	fi
	$(dirname ${0})/../convert-charsets-tools/generate-unicode-org-mappings-table.sh "${I%%:*}" ${NAME_PREFIX} > "${OUT}"
done
